### ISSUE TITLE
Атрибуты качества

### ISSUE THREAD

**Issue by AleshaShch** [OdareNNbI/Falling-box#2]
Как вы планируете проверять требования на основе информации, собранной по следующим атрибутам качества: "минималистический интерфейс",  "простой и понятный геймплей", "хорошая производительность"?

**Comment by OdareNNbI** [comment]
@AleshaShch минималистичный интерфейс - интерфейс без чёткой детализации UI. Простой и понятный геймплей - игрок должен понять как играть в игру за пару минут. Проверять эти два качества буду на людях. Давать играть и узнавать у них понятно играть либо же нет. Производительность буду проверять на разных девайсах.
